/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import org.hibernate.Session;
import org.hibernate.Transaction;

import models.config.HibernateUtil;

/**
 *
 * @author A663588
 */
public class BatchFiles extends javax.swing.JInternalFrame {

    /**
     * Creates new form BatchFiles
     */
    public BatchFiles () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Selectionner un fichier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton1ActionPerformed(evt);
				} catch (ClassNotFoundException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {
      
            
        	JFileChooser chooser = new JFileChooser();
 	        chooser.setApproveButtonText("Choix du fichier..."); 
 	            
 	        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
 	        	
 	        	System.out.println("FICHIER OK"+chooser.getSelectedFile().toString());
 	        	
 	        	String contenu="";
 	        	
 	        	String fichier=chooser.getSelectedFile().getAbsolutePath();
 	        	
 	        	try
 	        	 {
 	        		InputStream Fichier=new FileInputStream(fichier); 
 	        		InputStreamReader isrFichier=new InputStreamReader(Fichier);           
 	        	  
 	        		try (BufferedReader br=new BufferedReader(isrFichier))
 	        		{
 	        			String line;
 	        			 Connection con = null; 
	        	    	  Statement stmt = null; 
	        	    	  int result = 0; 
	        	    	  Class.forName("org.hsqldb.jdbc.JDBCDriver"); 
 	        	    	  con = DriverManager.getConnection( "jdbc:hsqldb:AppMedecins;hsqldb.lock_file=false", "sa", ""); 
 	        			while((line=br.readLine())!=null)
 	        			{
 	        	    		System.out.println(line);
 	        	    		contenu+=line+"\n";
 	        	    		  stmt = con.createStatement(); 
	 	        	    	  result = stmt.executeUpdate(line); 
	 	        	    	  con.commit(); 
	 	        	    	
	 	        	    	  System.out.println(result+" rows effected"); 
	 	        	    	  System.out.println("Rows inserted successfully"); 

 	        	    
 	        			}
 	        	        //JOptionPane.showMessageDialog(this, contenu, "Titre", JOptionPane.INFORMATION_MESSAGE);
 	        	  } 
 	        	 }
 	        
 	        	catch (IOException e)
 	        	{
 	        		 System.out.println(e.toString());
 	        	 }
 	        	
 	        }

        
		
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
