/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.List;
import java.util.Random;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import dao.AntecedantDAO;
import dao.ClasseAntecedantDAO;
import models.Antecedent;
import models.ClasseAntecedent;

/**
 *
 * @author A663588
 */
public class GeneratePDFAntecedant extends javax.swing.JInternalFrame {

    /**
     * Creates new form GeneratePDFAntecedant
     */
	
	DefaultTableModel model = new DefaultTableModel();
	boolean tableClick = false;
	String lib ="";
	
	public String genererChaineAleatoire() {
		String caracteres = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
		Random rand = new Random();
		
		int longueur = caracteres.length();
		String chaine ="";
		for(int i = 0; i < 6; i++) {
		  int k = rand.nextInt(longueur);
		 // System.out.print(caracteres.charAt(k));
		 chaine = chaine+ caracteres.charAt(k);
		}
		return chaine;
		
	}
	
	public void remplirTableANTECEDANT() {
        try {
            model.setRowCount(0);
            AntecedantDAO dao = new AntecedantDAO();

            model.setColumnIdentifiers(new String[]{"ID", "LIBELLE","CLASSE ANTECEDANT","CIM10"});

            List<Antecedent> antecedents = dao.getAllAntecedent();
            if (antecedents.size() > 0) {

                for (int i = 0; i < antecedents.size(); i++) {
                    model.addRow(new String[]{antecedents.get(i).getId().toString(), antecedents.get(i).getLibelle(),antecedents.get(i).getClasse().getLibelle(),antecedents.get(i).getCim10()});
                }
                tableAntecedant.setModel(model);
               // tableAntecedant.setEnabled(false);
            }else {
            	tableAntecedant.setEnabled(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
	
	
    public GeneratePDFAntecedant () {
        initComponents();
        model.setRowCount(0);
        remplirTableANTECEDANT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAntecedant = new javax.swing.JTable();

        jButton1.setText("GENERER PDF ANTECEDANT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableAntecedant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAntecedant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAntecedantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAntecedant);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
		
    	 String depotPDF ="C:\\Post de travail\\Dev Perso\\senegal Projet\\Projets\\AppMedecin\\MedecinsApp\\MedecinsApp\\src\\main\\java\\depotpdf\\"+genererChaineAleatoire()+".pdf";   
       	//System.out.print(depotPDF);
    	Document document = new Document();
    	PdfWriter.getInstance(document, new FileOutputStream(depotPDF));
    	// Ouverture doc
    	document.open();
    	
    	// Entete image 
    	Image image =Image.getInstance("C:\\Post de travail\\Dev Perso\\senegal Projet\\Projets\\AppMedecin\\MedecinsApp\\MedecinsApp\\src\\main\\java\\images\\entete.jpg");
    	image.scalePercent(15000f / image.getDpiX(), 7100f / image.getDpiY());
    	//image.setAbsolutePosition(0f, 0f); 
        //image.scaleAbsolute(600, 250);
    	document.add(image);
    	
    	// saut de ligne mais je vias creer une fontion pour dynaliser les choses on n'est en phase de test naar bi
    	document.add(new Paragraph(" "));
    	document.add(new Paragraph(" "));
    	
    
    	// Paragraph titre
    	Font font = new Font(FontFamily.HELVETICA, 12, Font.BOLD);
    	Paragraph paragraph = new Paragraph("GESTION MEDECIN",font);
    	paragraph.setAlignment(Element.ALIGN_CENTER);
    	document.add(paragraph);
    	
    	document.add(new Paragraph(" "));
    	document.add(new Paragraph(" "));
    	
    	// Ajout Tableau dans le document
    	 PdfPTable table = new PdfPTable(4);
    	 PdfPCell cell = new PdfPCell(new Phrase("ID"));
    	 table.addCell(cell);
    	    cell = new PdfPCell(new Phrase("LIBELLE"));
    	 table.addCell(cell);
    	    cell = new PdfPCell(new Phrase("CLASSE ANTECEDANT"));
    	 table.addCell(cell);
    	 	cell = new PdfPCell(new Phrase("CIM10"));
    	 table.addCell(cell);
    	 table.setHeaderRows(1);
    	 
    	 if(tableClick==true) {
    		 AntecedantDAO dao = new AntecedantDAO();
    		 Antecedent antecedent = dao.findAntecedant(lib);
    		 if(antecedent!=null) {
    			 table.addCell(""+antecedent.getId());
    			 table.addCell(antecedent.getLibelle());
    			 table.addCell(antecedent.getClasse().getLibelle());
    			 table.addCell(antecedent.getCim10());
    		 }
    	 }
	    		 
	    	 
    	// ajout donnée
	     document.add(table);
    	 	
    	document.close();
    	
    	System.out.print("FIN PDF");
    	
	} catch (Exception e) {
		System.out.println(e);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableAntecedantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAntecedantMouseClicked
    	 DefaultTableModel defaultTableModel = (DefaultTableModel) tableAntecedant.getModel();
	        int selectRowsIndex = tableAntecedant.getSelectedRow();
		            
	    	AntecedantDAO antecedantDAO = new AntecedantDAO();
			Antecedent antecedent = antecedantDAO.findAntecedant(defaultTableModel.getValueAt(selectRowsIndex, 1).toString());
			
			//JOptionPane.showMessageDialog (null, antecedent.getLibelle() , "TEST", JOptionPane.ERROR_MESSAGE);
				
			if(antecedent!=null) {
					lib =antecedent.getLibelle();
					tableClick = true;
					
				}else {
					JOptionPane.showMessageDialog (null, "ANTECEDANT "+antecedent.getId()+"N'EXISTE PAS", "GESTION PROFESSION" , JOptionPane.ERROR_MESSAGE);
				}    
    }//GEN-LAST:event_tableAntecedantMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAntecedant;
    // End of variables declaration//GEN-END:variables
}
