/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.ProfessionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Profession;

/**
 *
 * @author A663588
 */
public class GestionProfession extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProfession
     */
    DefaultTableModel model = new DefaultTableModel();
    Long idUpdateJtable;
    private static final Logger LOGGER = Logger.getLogger(GestionProfession.class.getName());
    private final String AJOUTER = "AJOUTER PROFESSION";
    private final String MODIFIER = "MODIFIER PROFESSION";
    private final String SUPPRIMER = "SUPPRIMER PROFESSION";
    private final ProfessionDAO PROFESSION_DAO;

    public void remplirTableProfession() {
        try {
            model.setRowCount(0);
            model.setColumnIdentifiers(new String[]{"ID", "LIBELLE"});

            List<Profession> professions = PROFESSION_DAO.findAll();
            for (int i = 0; i < professions.size(); i++) {
                model.addRow(new Object[]{professions.get(i).getId(), professions.get(i).getLibelle()});
            }
            tableProfession.setModel(model);

            tableProfession.getColumnModel().getColumn(0).setMinWidth(0);
            tableProfession.getColumnModel().getColumn(0).setMaxWidth(0);
            tableProfession.getColumnModel().getColumn(0).setWidth(0);
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, e.getMessage(), e);
        }

    }

    public void checkChoixSelect(String choixAction) {
        if (choixAction.equalsIgnoreCase("")) {
            desactiverChamps();
            choixBTX.setEnabled(false);
            choixBTX.setText("Aucune action");
        } else if (choixAction.equalsIgnoreCase(AJOUTER)) {
            activerChamps();
            choixBTX.setText(AJOUTER);
            choixBTX.setEnabled(true);
            activerChamps();
            viderChamps();
        } else if (choixAction.equalsIgnoreCase(MODIFIER)) {
            activerChamps();
            choixBTX.setText(MODIFIER);
            choixBTX.setEnabled(true);
            activerChamps();
            viderChamps();
        } else if (choixAction.equalsIgnoreCase(SUPPRIMER)) {
            activerChamps();
            choixBTX.setText(SUPPRIMER);
            choixBTX.setEnabled(true);
            desactiverChamps();
            viderChamps();
        }
    }

    public void remplirComboChoix() {
        comboChoixAction.removeAll();
        comboChoixAction.addItem("");
        comboChoixAction.addItem(AJOUTER);
        comboChoixAction.addItem(MODIFIER);
        comboChoixAction.addItem(SUPPRIMER);
        comboChoixAction.setSelectedIndex(0);
    }

    public void desactiverChamps() {
        libelle.setEnabled(false);
    }

    public void activerChamps() {
        libelle.setEnabled(true);
    }

    public void viderChamps() {
        libelle.setText("");
    }

    private void refreshAll() {
        desactiverChamps();
        remplirTableProfession();
        viderChamps();
    }

    public GestionProfession() {
        initComponents();
        this.PROFESSION_DAO = new ProfessionDAO();
        refreshAll();
        remplirComboChoix();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboChoixAction = new javax.swing.JComboBox<>();
        labelprofession = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        choixBTX = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProfession = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestion des professions");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Choix Action");

        comboChoixAction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboChoixAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChoixActionActionPerformed(evt);
            }
        });

        labelprofession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelprofession.setText("Nom de la profession");

        libelle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        choixBTX.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        choixBTX.setText("jButton1");
        choixBTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixBTXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choixBTX, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelprofession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(libelle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(comboChoixAction, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboChoixAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelprofession)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(choixBTX)
                .addContainerGap())
        );

        tableProfession.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableProfession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableProfession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableProfession.setEditingColumn(0);
        tableProfession.setEditingRow(0);
        tableProfession.setRowHeight(25);
        tableProfession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProfessionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProfession);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableProfessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProfessionMouseClicked
        idUpdateJtable = null;
        String choix = comboChoixAction.getSelectedItem().toString();
        if (choix.equals(MODIFIER) || choix.equals(SUPPRIMER)) {
            DefaultTableModel defaultTableModel = (DefaultTableModel) tableProfession.getModel();
            int selectRowsIndex = tableProfession.getSelectedRow();
            libelle.setText(defaultTableModel.getValueAt(selectRowsIndex, 1).toString());
            idUpdateJtable = (Long) defaultTableModel.getValueAt(selectRowsIndex, 0);
        } else if (choix.isEmpty()) {
            tableProfession.clearSelection();
            JOptionPane.showMessageDialog(this, "Merci de choisir une action", "Gestion des professions", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableProfessionMouseClicked

    private void comboChoixActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChoixActionActionPerformed
        checkChoixSelect(comboChoixAction.getSelectedItem().toString());
    }//GEN-LAST:event_comboChoixActionActionPerformed

    private void choixBTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixBTXActionPerformed

        if (choixBTX.getText().equals(AJOUTER)) {
            Profession professionCheck = PROFESSION_DAO.findByLibelle(libelle.getText());

            if (professionCheck != null) {
                JOptionPane.showMessageDialog(null, "CETTE PROFESSION EXISTE DEJA MERCI !", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
            } else {
                //System.out.println("Libelle :  null");
                Profession newProfession = new Profession();
                newProfession.setLibelle(libelle.getText());
                if (PROFESSION_DAO.save(newProfession)) {
                    JOptionPane.showMessageDialog(null, "PROFESSION AJOUTEE AVEC SUCCES", "GESTION PROFESSION", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "ECHEC DE LA CREATION DE LA PROFESSION", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (choixBTX.getText().equalsIgnoreCase(MODIFIER)) {
            if (libelle.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "LE LIBELLE NE DOIT PAS ETRE VIDE !", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
            } else if (idUpdateJtable == null) {
                JOptionPane.showMessageDialog(null, "CHAMP SELECTIONNE INTROUVABLE", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
            } else {
                Profession newProfession = new Profession();
                newProfession.setId(idUpdateJtable);
                newProfession.setLibelle(libelle.getText());
                PROFESSION_DAO.updateProfession(newProfession);
                JOptionPane.showMessageDialog(null, "PROFESSION MODIFIEE AVEC SUCCESS", "GESTION PROFESSION", JOptionPane.INFORMATION_MESSAGE);
            }

        } else if (choixBTX.getText().equalsIgnoreCase(SUPPRIMER)) {
            if (idUpdateJtable == null) {
                JOptionPane.showMessageDialog(null, "CHAMP SELECTIONNE INTROUVABLE", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
            } else {
                Profession newProfession = new Profession();
                newProfession.setId(idUpdateJtable);
                newProfession.setLibelle(libelle.getText());
                if (PROFESSION_DAO.deleteProfession(newProfession)) {
                    JOptionPane.showMessageDialog(null, "PROFESSION SUPRIMEE AVEC SUCCESS", "GESTION PROFESSION", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "ECHEC DE LA SUPPRESSION", "GESTION PROFESSION", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        tableProfession.clearSelection();
        refreshAll();
        comboChoixAction.setSelectedIndex(0);
        choixBTX.setText("Aucune action");
        choixBTX.setEnabled(false);
        idUpdateJtable = null;
    }//GEN-LAST:event_choixBTXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choixBTX;
    private javax.swing.JComboBox<String> comboChoixAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelprofession;
    private javax.swing.JTextField libelle;
    private javax.swing.JTable tableProfession;
    // End of variables declaration//GEN-END:variables
}
